version: '3.8'

services:
  devices:
    build:
      context: ./devicesService
      dockerfile: Dockerfile
    env_file:
      - ./devicesService/.env
    volumes:
      - ./devicesService:/app
    network_mode: "host"
    # networks:
    #   - devicesNet

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devices
    networks:
      - devicesNet

networks:
  devicesNet:
    driver: bridge
