version: '3.8'

services:
  devices:
    build:
      context: ./devicesService
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./devicesService/.env
    volumes:
      - ./devicesService:/app
    networks:
      - devicesNet

  devicesDB:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devices
    networks:
      - devicesNet

networks:
  devicesNet:
    driver: bridge
